### ISSUE TITLE
Logs line number in jdl file that cause error when use jdl-import command to parse jdl file

### ISSUE THREAD

**Issue by nghib** [jhipster/jhipster-core#91] opened 2016-11-30 05:32 UTC
For example that create error log bellow. It's good if we can log the line number inside domain.jh file that cause error.

$yo jhipster:import-jdl domain.jh
The jdl is being parsed.
{ name: 'NullPointerException',
  message: 'The type, and at least one injected field must be passed.',
  prototype:
   Error
       at new buildException (/Users/myusername/spring/generator-jhipster/node_modules/jhipster-core/lib/exceptions/exception_factory.js:43:25)
       at new JDLRelationship (/Users/myusername/spring/generator-jhipster/node_modules/jhipster-core/lib/core/jdl_relationship.js:19:13)
       at fillAssociations (/Users/myusername/spring/generator-jhipster/node_modules/jhipster-core/lib/parser/jdl_parser.js:155:31)
       at Object.parse [as convertToJDL] (/Users/myusername/spring/generator-jhipster/node_modules/jhipster-core/lib/parser/jdl_parser.js:41:3)
       at constructor.parseJDL (/Users/myusername/spring/generator-jhipster/generators/import-jdl/index.js:45:41)
       at Object.<anonymous> (/Users/myusername/spring/generator-jhipster/node_modules/yeoman-generator/lib/base.js:439:23)
       at /Users/myusername/spring/generator-jhipster/node_modules/yeoman-generator/node_modules/run-async/index.js:26:25
       at /Users/myusername/spring/generator-jhipster/node_modules/yeoman-generator/node_modules/run-async/index.js:25:19
       at /Users/myusername/spring/generator-jhipster/node_modules/yeoman-generator/lib/base.js:440:9
       at runCallback (timers.js:637:20) }
Error jhipster:import-jdl domain.jh

**Comment by MathieuAA** [comment] 2016-11-30 08:40
I'll see why the submodule doesn't print the line numbers...

**Comment by MathieuAA** [comment] 2016-11-30 20:20
Quick question, what version of the generator are you using? Because [466315](https://github.com/jhipster/generator-jhipster/commit/b466315a0d89da7da938a3bcc478f920965009f6) has been added a few days ago.

**Comment by nghib** [comment] 2016-12-01 01:14
I tested with Jhipster 3.12.0 released version. This is my simple domain.jh file. The exception will be throw in "relationship" section - line 12 

entity Challenge {
    createDate ZonedDateTime,
    endDate ZonedDateTime,
    description String
}

entity Response {
    name String
}

relationship ManyToOne {
    Response to Challenge
}

**Comment by MathieuAA** [comment] 2016-12-01 06:33
Okay that's weird... I'll work on something this evening for your issue.

Le 1 décembre 2016 02:14:19 GMT+01:00, Phuc Bui <notifications@github.com> a écrit :
>I tested with Jhipster 3.12.0 released version. This is my simple
>domain.jh file. The exception will be throw in "relationship" section -
>line 12 
>
>entity Challenge {
>    createDate ZonedDateTime,
>    endDate ZonedDateTime,
>    description String
>}
>
>entity Response {
>    name String
>}
>
>relationship ManyToOne {
>    Response to Challenge
>}
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-core/issues/91#issuecomment-264049180

-- 
Mathieu ABOU-AICHI

**Comment by nghib** [comment] 2016-12-01 07:51
it's not an issue, it's about improvement ;). you're doing great job. ;)

**Comment by MathieuAA** [comment] 2016-12-01 21:13
Well... it it was supposed to work before and not anymore, then something must have gone wrong, right? :) I'm not the maintainer of the submodule, but I'm taking a look at it right now to see where it can be improved.

**Comment by MathieuAA** [comment] 2016-12-01 22:01
My error when I use the submodule from v3.9.1:
```
The jdl is being parsed.
The type, and at least one injected field must be passed.
Error jhipster:import-jdl test.jdl 

ERROR! 
Error while parsing entities from JDL
```
This looks prettier than what you have...

**Comment by MathieuAA** [comment] 2016-12-01 22:09
Oh I get it. You don't have any indication because it's not a syntax error. You'd have the line then... I'll improve the parser to try to include the line, or at least to provide more information about any error.

**Comment by bourdux** [comment] 2017-01-01 19:21
:+1: Yes, I think that would be a good idea. If you look to the source code of the generator, you usually end up understanding the error but having the culprit line would really help.

Just another example: in the JH file I recently made I wrote:

```service all with ServiceClass``` instead of ```service all with serviceClass```.

The result was this error

```
The jdl is being parsed.
{ name: 'IllegalArgumentException',
  message: 'The option\'s name and value must be valid.',
  prototype: [Error] }
Error jhipster:import-jdl plplus.jh 

ERROR! 
Error while parsing entities from JDL
```

I tracked down the error by a simple visit to  https://github.com/jhipster/jhipster-core/blob/master/lib/core/jdl_binary_option.js#L15 and then to https://github.com/jhipster/jhipster-core/blob/master/lib/core/jhipster/binary_options.js#L15 but displaying the line number at fault would really have helped especially since my definition file is close to 300 lines :)

**Comment by MathieuAA** [comment] 2017-01-02 10:49
My vacations will unfortunately be over very soon and I'll try some things to pinpoint errors. Please do keep in mind that we may not get as precise as having the line at fault, as there's some preprocessing involved here.

Le 1 janvier 2017 20:21:11 GMT+01:00, Julien Bourdon <notifications@github.com> a écrit :
>:+1: Yes, I think that would be a good idea. If you look to the source
>code of the generator, you usually end up understanding the error but
>having the culprit line would really help.
>
>Just another example: in the JH file I recently made I wrote:
>
>```service all with ServiceClass``` instead of ```service all with
>serviceClass```.
>
>The result was this error
>
>```
>The jdl is being parsed.
>{ name: 'IllegalArgumentException',
>  message: 'The option\'s name and value must be valid.',
>  prototype: [Error] }
>Error jhipster:import-jdl plplus.jh 
>
>ERROR! 
>Error while parsing entities from JDL
>```
>
>I tracked down the error by a simple visit to 
>https://github.com/jhipster/jhipster-core/blob/master/lib/core/jdl_binary_option.js#L15
>and then to
>https://github.com/jhipster/jhipster-core/blob/master/lib/core/jhipster/binary_options.js#L15
>but displaying the line number at fault would really have helped
>especially since my definition file is close to 300 lines :)
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-core/issues/91#issuecomment-269915641

-- 
Mathieu ABOU-AICHI
-- 
Mathieu ABOU-AICHI

**Comment by MathieuAA** [comment] 2017-01-02 10:50
My vacations will unfortunately be over very soon and I'll try some things to pinpoint errors. Please do keep in mind that we may not get as precise as having the line at fault, as there's some preprocessing involved here.

Le 1 janvier 2017 20:21:11 GMT+01:00, Julien Bourdon <notifications@github.com> a écrit :
>:+1: Yes, I think that would be a good idea. If you look to the source
>code of the generator, you usually end up understanding the error but
>having the culprit line would really help.
>
>Just another example: in the JH file I recently made I wrote:
>
>```service all with ServiceClass``` instead of ```service all with
>serviceClass```.
>
>The result was this error
>
>```
>The jdl is being parsed.
>{ name: 'IllegalArgumentException',
>  message: 'The option\'s name and value must be valid.',
>  prototype: [Error] }
>Error jhipster:import-jdl plplus.jh 
>
>ERROR! 
>Error while parsing entities from JDL
>```
>
>I tracked down the error by a simple visit to 
>https://github.com/jhipster/jhipster-core/blob/master/lib/core/jdl_binary_option.js#L15
>and then to
>https://github.com/jhipster/jhipster-core/blob/master/lib/core/jhipster/binary_options.js#L15
>but displaying the line number at fault would really have helped
>especially since my definition file is close to 300 lines :)
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-core/issues/91#issuecomment-269915641

-- 
Mathieu ABOU-AICHI

**Comment by MathieuAA** [comment] 2017-01-04 18:37
I did some digging, and there's no foreseeable to get the line with PegJS (because of the preprocessing).
There is, however, another way:
  - We read the file (with the Node API),
  - We keep a line-oriented record of the file (with the lines),
  - As soon as we get an error, we search the lines for some keywords (`ServiceClass`, `mapstruc`, or whatever triggered an error),
  - We display the result of the search.

This is the easiest way to do that without adding constants to the grammar, which I don't want.

**Comment by deepu105** [comment] 2017-01-04 20:38
The jdl studio outputs error with line numbers you could take look to see
the implementation

Thanks & regards,
Deepu

**Comment by kaidohallik** [comment] 2017-01-04 20:57
So workaround while this enhancement is not implemented in jhipster:import-jdl is to copy .jdl file to JDL Studio and JDL Studio outputs line number where error occurs.

**Comment by MathieuAA** [comment] 2017-01-04 21:35
No. There's another way. Quite stupid of me not to have thought about it earlier. I'll use JHipster Core in the JDL parsing.

**Comment by SgElite** [comment] 2017-04-08 10:08
Hi, I encounter the following error while doing a jdl import, could not figured out what is the issue. Anyone care to enlighten ? 
----------------------------------------------------------------------------------------------------------------
{ name: 'IllegalArgumentException',
  message: 'The option\'s name and value must be valid.',
  prototype:
   Error
       at new buildException (D:\Workspace\jhipster-apps\project-s2c2\node_modules\jhipster-core\lib\exceptions\exception_factory.js:43:25)
----------------------------------------------------------------------------------------------------------------
[jhipster-jdl-08042017.zip](https://github.com/jhipster/jhipster-core/files/907358/jhipster-jdl-08042017.zip)

**Comment by MathieuAA** [comment] 2017-04-09 12:17
I'm gonna change some error messages to fix this problem.

**Comment by MathieuAA** [comment] 2017-04-09 20:18
I've improve error reportings (still unfinished), and it will be released in v1.3.
Logging line numbers is actually not a good idea as the JDL processor actually reads after the parsing is done.

**Comment by MathieuAA** [comment] 2017-04-14 20:34
Closing this as it will happen in v1.3.0 (released this week-end).

**Closed by MathieuAA** 2017-04-14 20:34 UTC
Labels: enhancement

**Comment by vw98075** [comment] 2017-05-30 02:37
I run into the same error. It hard to tell what is the cause without a line number.

**Comment by MathieuAA** [comment] 2017-05-30 07:11
What's your generator's version?

**Comment by vw98075** [comment] 2017-05-31 15:23
The latest one, 4.5.2.

**Comment by MathieuAA** [comment] 2017-06-04 16:02
@vw98075 can you open a new issue and provide your JDL file?
