### ISSUE TITLE
The entity(table_name) of JDL can't work well  --"entity B (the_best_entity) // the_best_entity is the table's name"

### ISSUE THREAD

**Issue by yuedefeng** [jhipster/jhipster-core#19] opened 2016-05-16 03:17 UTC
https://jhipster.github.io/jdl/

entity B (the_best_entity) // the_best_entity is the table's name

my code:

entity Activity (cs_activity)  {	
    activityId Integer required ,
    activityTitle String required maxlength(255),
    activityType String  ,
    activityBanner String required maxlength(255),
    activityStyle String required maxlength(255),
    activityDesc String required maxlength(1000),
    activityStartDate Integer required ,
    activityEndDate Integer required ,
    activitySort Integer required ,
    activityState Integer required 
  } 

yo jhipster:import-jdl yourfile.jh

**Comment by flying3615** [comment] 2016-05-16 05:18
paste exception trace here

{ gateway }  » yo jhipster:import-jdl dbentity.jh                                     /cygdrive/e/project/jhipster_micro/gateway
The jdl is being imported.
SyntaxError: Expected "/*", "//", "dto", "entity", "enum", "paginate", "relationship", "service", "{", a space or end of input but "(" found.
    at peg$buildException (C:\Users\centling\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\jhipster-uml\lib\dsl\jhGrammar.js:364:14)
    at Object.peg$parse [as parse] (C:\Users\centling\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\jhipster-uml\lib\dsl\jhGrammar.js:4403:13)
    at DSLParser.parse (C:\Users\centling\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\jhipster-uml\lib\dsl\dsl_parser.js:30:27)
    at module.exports.JDLGenerator.extend.default.parseJDL (C:\Users\centling\AppData\Roaming\npm\node_modules\generator-jhipster\generators\import-jdl\index.js:65:37)
    at Object.<anonymous> (C:\Users\centling\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\base.js:436:25)
    at C:\Users\centling\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\node_modules\run-async\index.js:26:25
    at C:\Users\centling\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\node_modules\run-async\index.js:25:19
    at C:\Users\centling\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\base.js:448:8
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by MathieuAA** [comment] 2016-05-17 06:43
Sorry, I was on holidays and didn't want to check my mails.
I'll reproduce it and fix it.
Thanks for reporting this.

**Comment by MathieuAA** [comment] 2016-05-28 09:58
Hello, this issue will have to be checked after work on core objects is done and the JDL parser is moved here. However, it looks like a subgen issue because they don't share everything yet.

**Comment by gruenewald** [comment] 2016-06-20 11:28
Hi @MathieuAA ,
i have the same issue. Is there a workaround to generate the jhipster-Files with the adapted table names? Do you have an approximate schedule when the error will be corrected? Thanks for this nice JDL!

**Comment by MathieuAA** [comment] 2016-06-20 11:44
Hi! It should be fixed as soon as the subgen uses this project. In the meantime, you cam use JHipster UML to process your entities. We are working to get this released ASAP, but I don't have an ETA on this.

Le 20 juin 2016 13:28:11 GMT+02:00, "Matthias Grünewald" <notifications@github.com> a écrit :
>Hi @MathieuAA ,
>i have the same issue. Is there a workaround to generate the
>jhipster-Files with the adapted table names? Do you have an approximate
>schedule when the error will be corrected? Thanks for this nice JDL!
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-domain-language/issues/19#issuecomment-227117265

-- 
Mathieu ABOU-AICHI

**Comment by MathieuAA** [comment] 2016-07-04 22:12
The feature lacking in the subgen has been implemented in the dev branch, which should be released very, very, very soon (today or tomorrow). Therefore, I'm closing this. Thanks to all of you for reporting this!

**Comment by davidweianibone** [comment] 2016-10-04 08:13
Hi Mathieu, was this issue solved ? I am also facing this issue

**Comment by MathieuAA** [comment] 2016-10-04 08:25
What? Again? It has already been released... Are you sure you're using the last version of JHipster?

**Comment by davidweianibone** [comment] 2016-10-04 08:29
yes. I am new with JHispter. Just installed it two days ago

**Comment by MathieuAA** [comment] 2016-10-04 08:33
I'll reopen this in a "to test" state. I'll test it tonight.

**Comment by davidweianibone** [comment] 2016-10-04 08:36
Thanks a lot :) waiting for your test results and reply

**Comment by MathieuAA** [comment] 2016-10-05 08:41
Hi, I didn't have any issue with grammar... are you sure it's the same stacktrace? if not, please create a new issue and give us all the information we might need.

**Comment by davidweianibone** [comment] 2016-10-05 22:24
Thanks Mathieu, I will try again tomorrow and let you know

**Comment by MathieuAA** [comment] 2016-10-06 04:56
I forgot: is it the same JDL? if it differs, then you might have found a bug.

**Comment by davidweianibone** [comment] 2016-10-06 05:12
Same one as in JHipster studio. Not sure if it matters, but it was on a monolithic App. 
I have created a new microservice and will try the JDL again today

**Comment by MathieuAA** [comment] 2016-10-06 06:39
Oh. What does matter is the fact that the problem seems to happen when one uses the JDL-Studio. @deepu105 can you investigate please?

**Comment by deepu105** [comment] 2016-10-06 07:14
First of all there is no such sample in JDL studio, second I do not do any processiing on the JDL content its exported as it is. Third @davidweianibone hasnt given any useful info like JDL file, stack trace etc for us to investigate
@davidweianibone if you have an issue please open a new ticket with JDL used and error stack trace and steps to reproduce

**Closed by deepu105** 2016-10-06 07:14 UTC
