### ISSUE TITLE
better microservice flow for JDL

### ISSUE THREAD

**Issue by xetys** [jhipster/jhipster-core#106] opened 2017-02-12 20:05 UTC
Hey, 

I played a bit with the microservice JDL and figured out, that it is only cool to use this feature on a gateway, but not for all microservices. From my intuition I dropped a JDL file in a root with several JHipster app, and expected this file will generate only mentioned entities in the target folder. Consider a JDL modelling all entities for a bookstore. It should only import those services into .jhipster, which are mentioned by

`microservice * with <this-app>`

like `Book` for `BookService`

Currently, this workflow generated all entities in that file.

Alternatively, the JDL subgenerator may ask which entities to generate.

**Comment by MathieuAA** [comment] 2017-02-12 21:28
I like the idea. I prefer having separate JDL files though and placing them in each project though.
I'll see what I can do to make it happen, but we need to upgrade the subgen to make it more interesting.
Nice idea =)

Le 12 février 2017 21:05:41 GMT+01:00, David Steiman <notifications@github.com> a écrit :
>Hey, 
>
>I played a bit with the microservice JDL and figured out, that it is
>only cool to use this feature on a gateway, but not for all
>microservices. From my intuition I dropped a JDL file in a root with
>several JHipster app, and expected this file will generate only
>mentioned entities in the target folder. Consider a JDL modelling all
>entities for a bookstore. It should only import those services into
>.jhipster, which are mentioned by
>
>`microservice * with <this-app>`
>
>Currently, this workflow generated all entities in that file.
>
>Alternatively, the JDL subgenerator may ask which entities to generate.
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-core/issues/106

-- 
Mathieu ABOU-AICHI

**Comment by MathieuAA** [comment] 2017-02-13 21:30
Work is being done in the "106" branch.

**Comment by xetys** [comment] 2017-02-14 08:45
thanks a lot!

**Comment by MathieuAA** [comment] 2017-02-19 09:44
Deepu's solution is the only one we can implement. 
It's going to be like this:
```
entity A
entity B
microservice * with something(../SomethingService) 
```

**Comment by xetys** [comment] 2017-02-19 14:06
I am ok with this....but then we should precisely document, how a user should design the directory structure and how to use it properly

**Comment by MathieuAA** [comment] 2017-02-19 14:57
Indeed. But it's the easy part =)

Le 19 février 2017 15:06:33 GMT+01:00, David Steiman <notifications@github.com> a écrit :
>I am ok with this....but then we should precisely document, how a user
>should design the directory structure and how to use it properly
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-core/issues/106#issuecomment-280921270

-- 
Mathieu ABOU-AICHI

**Comment by MathieuAA** [comment] 2017-02-20 07:40
@xetys Having your point in mind, the most important part, in my opinion, would be to define a convention: where a microservice should be (inside a gateway project, in the same directory, etc.).

**Comment by xetys** [comment] 2017-02-20 11:45
my work flow was to have a folder structure like in this repo: https://github.com/xetys/microxchng-workshop

I would prefer to keep just the app.jh in the root, and refer to it with

```
$ yo jhipster:impport-jdl ../app.jh
```

from each subdir...

**Comment by PierreBesson** [comment] 2017-02-20 12:54
I think we can standardise on the folder structure shown by @xetys with all projects at the same root, but I would organize the entities by service in a separate `entities` folder.
- gateway
- microservice1
- microservice2
- deployment
  - docker
  - kubernetes
  - rancher
- entities
  - microservice1
  - microservice2

Eventually microservice1, microservice2 could be in separate git repositories or in git sub-modules (which I don't like because they are confusing) so the solution with JDL should be able to be adapted to other paths...

**Comment by MathieuAA** [comment] 2017-02-20 13:25
You could do that... But JHipster is not _yet_ designed like that... And it would complicate things with the entity generation process. Otherwise I agree that having conventions is a good thing.

Le 20 février 2017 13:54:05 GMT+01:00, Pierre Besson <notifications@github.com> a écrit :
>I think we can standardise on the folder structure shown by @xetys with
>all projects at the same root, but I would organize the entities by
>service in a separate `entities` folder.
>- gateway
>- microservice1
>- microservice2
>- deployment
>  - docker
>  - kubernetes
>  - rancher
>- entities
>  - microservice1
>  - microservice2
>
>Eventually microservice1, microservice2 could be in separate git
>repositories or in git sub-modules (which I don't like because they are
>confusing) so the solution with JDL should be able to be adapted to
>other paths...
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-core/issues/106#issuecomment-281072069

-- 
Mathieu ABOU-AICHI

**Comment by MathieuAA** [comment] 2017-02-20 14:32
@PierreBesson We could use such an architecture if we can generate an app from the JDL (soon) and if we could generate several apps from one JDL (it would be a kickstarting process). However, not using several JDL files is ugly as hell... there may be one day when JDL files can be called from on single file.

**Comment by xetys** [comment] 2017-02-20 21:33
My initial idea is actually about not generating unwanted entities for one JDL...which does **not** exclude the approach of using multiple JDLs. 

For example I may design one JDL for each bounded context of my domain, which still can be realized with several microservices.

However, I am not fully convinced about the path requirement in JDL, as well as forcing a particular directory structure....

**Comment by MathieuAA** [comment] 2017-02-21 06:07
Forcing? Nop. The idea is to introduce a convention when not using the path (same dir). I could also tell you you misused the jdl import subgen by not splitting the jdl in several pieces and using several times the jdl import process, but I would be wrong. That's why the path is needed, because there's no fixed directory placement (and it shouldn't ever be one).

Le 20 février 2017 22:33:06 GMT+01:00, David Steiman <notifications@github.com> a écrit :
>My initial idea is actually about not generating unwanted entities for
>one JDL...which does **not** exclude the approach of using multiple
>JDLs. 
>
>For example I may design one JDL for each bounded context of my domain,
>which still can be realized with several microservices.
>
>However, I am not fully convinced about the path requirement in JDL, as
>well as forcing a particular directory structure....
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-core/issues/106#issuecomment-281186029

-- 
Mathieu ABOU-AICHI

**Comment by Rostom35** [comment] 2017-06-23 13:10
Hi guys! I have some issues using the JDL generator for a microservice architecture. Indeed, I want to create two microservices (with respectively entity A and entity B)  + a service inside the gateway (with entity C).
The problem I am facing is that I can't generate properly this architecture using the JDL generator.
Here is basically how relations look like :
C -> A -> B ( I have three database sql )

I didn't found something that could help me in the documentation, that why I am here.

note : I have test several case of generation, if you have an idea of how to do this kind of architecture that will be fantastic.

Thank you.

**Comment by jdubois** [comment] 2017-06-23 13:12
@Rostom35 I'm sorry but this isn't a bug, can you use Stackoverflow instead, as explained in our guidelines?

**Comment by jdubois** [comment] 2017-06-23 13:13
@Rostom35 why did you comment on another issue? I closed this issue because of you :-(
Please follow the guidelines

**Comment by jdubois** [comment] 2017-09-29 16:05
I have a related issue with microservices -> @MathieuAA please tell me if you think this needs to be another ticket.

When I generate an entity in a microservice, for example:

```
entity Cart {
	customerId Long required
}
```

This generates the following JSON file:
```
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "customerId",
            "fieldType": "Long",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20170929153102",
    "entityTableName": "cart",
    "dto": "no",
    "pagination": "no",
    "service": "no"
}
```

But this should also include, with "micro1" being the name of the current application (only for applications of type "microservice"):
```
    "microserviceName": "micro1",
```

By adding this, it allows to generate the same entity on a Gateway: I can run "jhipster entity Cart" on the Gateway and point to my microservice. Otherwise, the Gateway won't find the microservice name, and the generation will fail.

I think this is very important for being able to use the JDL with microservices.

**Comment by deepu105** [comment] 2017-09-29 17:32
@jdubois I think its already possible in JDL see http://www.jhipster.tech/jdl/#microserviceoptions

**Comment by deepu105** [comment] 2017-09-29 17:38
Unless you are talking about something different!

**Comment by jdubois** [comment] 2017-09-29 18:10
No it's different :-)
When I import my JDL, I would like this property (which is in fact the URL to the microservice) to be added automatically into the .json file, when the application type is "microservice".

**Comment by PierreBesson** [comment] 2017-09-29 23:10
@jdubois. Yes it would be nice to have but I think this would only matter for the export-jdl subgen. Because when you import a microservice entity on the gateway, it already adds the correct microserviceName. And when you create entities with JDL. The microserviceName property only matter for the gateway not the microservice itself.

**Comment by deepu105** [comment] 2017-09-30 09:23
Oh ok got it, probably it needs to be done on the generator code for entity

**Comment by jdubois** [comment] 2017-09-30 09:31
@PierreBesson no did does work (I thought it did), when you do it like that:

- I create an entity in a microservice using the JDL -> that doesn't add the `microserviceName` in the `.json` file
- So then when I create the same entity in the gateway, using the command-line, it can't find the microservice name, and so it fails

**Comment by MathieuAA** [comment] 2017-09-30 11:22
@jdubois this may very well be a regression, let me have a look and I'll get back to you.

**Comment by MathieuAA** [comment] 2017-09-30 11:29
@jdubois how silly of me: this is an enhancement. I'll add it ASAP.

**Comment by MathieuAA** [comment] 2017-09-30 13:17
@jdubois @deepu105 @PierreBesson: it's done. I'll propose a change for the subgen now.

**Comment by MathieuAA** [comment] 2018-05-30 18:38
Closing this, as the app + entity file generation will be fixed in JCore v3, to be released tomorrow.

**Closed by MathieuAA** 2018-05-30 18:38 UTC
Labels: enhancement
