### ISSUE TITLE
Not able to add nativeLanguage to jdl application

### ISSUE THREAD

**Issue by DanielFran** [jhipster/jhipster-core#233] opened 2018-06-24 22:32 UTC
### The issue
Not able to add nativeLanguage to jdl application

Define application in jdl, seems not accept nativeLanguage variable
---

### Motivation for or Use Case

---

### Reproduce the error
Use the jdl definition bellow, it works without the nativeLanguage.

---

### Related issues

---

### Suggest a Fix

---

### The JDL file
application {
  config {
    jhipsterVersion 5.0.0
    baseName myApp
    applicationType microservice
    packageName io.test.myapp
    serverPort 8080
    authenticationType jwt
    cacheProvider no
    enableHibernateCache false
    databaseType sql
    devDatabaseType h2Memory
    prodDatabaseType postgresql
    searchEngine false
    messageBroker false
    serviceDiscoveryType false
    buildTool maven
    enableSwaggerCodegen false
    enableTranslation true
    **nativeLanguage en**
    languages [en, fr]
    testFrameworks [ ]
    jhiPrefix jhi
    clientPackageManager npm
    skipClient true
    skipServer false
    skipUserManagement true
    websocket false
  }
  
  entities *
}

---

### Versions 

| JHipster           |
| ------------------ |
| `5.0.0` |

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment] 2018-06-25 08:49
I'll add it for the next release, thanks!

**Comment by MathieuAA** [comment] 2018-06-25 16:34
Okay, it was added but there was a bug in the grammar. As there's migration going on, I'll check this doesn't happen.

**Comment by MathieuAA** [comment] 2018-06-25 18:46
@bd82 here the issue is about arrays. The new parsing system has to support these kinds of forms:
  - `[]`
  - `[a, b, c]`
  - `a, b, c`

Do you have an idea on how to do it wit chevrotain?

**Comment by bd82** [comment] 2018-06-25 20:15
Hi @MathieuAA 

Long reply incoming 😄 

## Pegjs Parser
I am not convinced the old system actually supports these forms.
I saw this recent [commit](https://github.com/jhipster/jhipster-core/commit/05a907747870a9d2d7a662c773752419d475e1e0#diff-6fe18b15e89d86c747be91dfceee7a84R264)
and if I understand correct the forms supported in 3.0.2 are:
* ``` [a, b, c]``` - valid with braces
* ```[ a, b, c```  - missing closing braces
* ```a, b, c ]```  - missing opening braces
* ```a, b, c```  - valid no braces at all

## Ambiguity 
The last form is very problematic because it makes the comma separator ambiguous:  
* Is it a comma between array items?
* Is it a comma between config elements?

Example:

```
application foo {
   config {
     packageName foo.bar,
     languages a, b, c, // what does the last comma belong to?
     baseName helloWorld    
   }
}
```

In the Peg grammar this is "resolved" using whitespace sensitivity because there cannot be any
line terminators in an array, so an array would always have to be in one line (even if it has 50 elements)...

We can solve it the same way in the Chevrotain grammar but this means adding whitespace sensitivity to the grammar.  We can also solve it by adding a GATE, meaning before "choosing" to consume
another element in the array we will check that the next element is **not** a config key. (more on this later)

The second option is prettier, but in general I can't recommend supporting **bare** arrays without braces, generally if something is ambiguous for a computer to understand it would probably be so for a human too and I am a big believer in keeping things simple.

## Chevrotain Parser

It currently only supports:
* ```[a, b, c]```

This is the related code:
```javascript
    $.RULE('list', () => {
      $.CONSUME(LexerTokens.LSQUARE);
      $.AT_LEAST_ONE_SEP({
        SEP: LexerTokens.COMMA,
        DEF: () => {
          $.CONSUME(LexerTokens.NAME);
        }
      });
      $.CONSUME(LexerTokens.RSQUARE);
});
```

To support empty arrays simply change **AT_LEAST_ONE_SEP** to **MANY_SEP**

I will try to provide a snippet showing general direction of supporting "bare" (braceless) arrays
later, but again I strongly discourage against it, it start smelling like the strange context specific rules present in the YAML grammar 😢

**Comment by deepu105** [comment] 2018-06-25 20:22
My 2 cents.

I guess it indeed is simple to have the braces for array values, and since
our users are technical folks it shouldn't matter to them.

I think having a robust grammar is more important than a pretty one

**Comment by MathieuAA** [comment] 2018-06-25 20:36
Okay, there was an issue with the previous grammar, and it wasn't really supported. So I guess making the braces mandatory isn't really a breaking change.I've tried the MANY_SEP, and there was an error (gonna try to fix it tomorrow).Le 25 juin 2018 22:22, Deepu K Sasidharan <notifications@github.com> a écrit :My 2 cents.

I guess it indeed is simple to have the braces for array values, and since
our users are technical folks it shouldn't matter to them.

I think having a robust grammar is more important than a pretty one

**Comment by bd82** [comment] 2018-06-25 21:03
> I think having a robust grammar is more important than a pretty one

👍

**Comment by MathieuAA** [comment] 2018-06-25 21:53
Okay, sometimes there's no children name check. That's why it fails. Gonna fix it.

**Comment by bd82** [comment] 2018-06-25 23:37
> Okay, sometimes there's no children name check. That's why it fails. Gonna fix it.

Makes sense if there was an assumption the elements array is none empty

**Comment by colameo** [comment] 2018-06-26 06:36
About arrays, I had the same issue in the JH IDE and had to work around that (I could only solve it by implementing “logic” behind to get rid of ambiguities):
<img width="698" alt="screen shot 2018-06-26 at 08 31 01" src="https://user-images.githubusercontent.com/629760/41893230-5127307e-791b-11e8-8836-c85b4c6293ab.png">
However, I want to release my stuff soon and need an official documentation of the application config stuff.

**Comment by MathieuAA** [comment] 2018-06-26 07:35
I'll do that today. I've fixed my issue with arrays yesterday after debugging.Le 26 juin 2018 08:36, Serano Colameo <notifications@github.com> a écrit :About arrays, I had the same issue in the JH IDE and had to work around that (I could only solve it by implementing “logic” behind to get rid of ambiguities):

However, I want to release my stuff soon and need an official documentation of the application config stuff.

**Comment by MathieuAA** [comment] 2018-06-26 11:18
Closing this issue. I'll update the doc right away.

**Closed** 2018-06-26 11:20 UTC
Labels: bug
